#:schema node_modules/wrangler/config-schema.json
name = "local-wrangler"
compatibility_date = "2024-08-12"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "D1_DB"
database_name = "local-d1-db"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
preview_database_id = "D1_DB" 
migrations_dir = "./db/sql-migrations"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "local-r2-bucket"
preview_bucket_name = "R2_BUCKET"
# jurisdiction = ""


[vars]
API_HOST = "example.com"